FROM rasa/rasa:3.6.21-full

WORKDIR /app

# Copy code
COPY . /app

# Create models folder
RUN mkdir -p /app/models

# Download model from GitHub Release using curl (wget missing)
RUN curl -L https://github.com/Unknownerror-test-500/test/releases/download/Chatbot/20251116-212136-tender-chain.tar.gz \
    -o /tmp/model.tar.gz && \
    tar -xzf /tmp/model.tar.gz -C /app/models
    RUN ls /app/models

# Install requirements
RUN pip install --no-cache-dir -r requirements.txt || true

EXPOSE 5005

CMD ["run", "--enable-api", "--cors", "*", "--debug", "-p", "5005", "-i", "0.0.0.0"]